---

    - name: Install prerequisite packages
      package:
        name:
          - unzip
        state: present
      when: ansible_facts['os_family'] in ['Debian', 'RedHat']

    - name: Download Promtail binary
      ansible.builtin.get_url:
        url: https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-amd64.zip
        dest: /tmp/promtail-linux-amd64.zip

    - name: Unzip Promtail binary
      ansible.builtin.unarchive:
        src: /tmp/promtail-linux-amd64.zip
        dest: /usr/local/bin/
        remote_src: true

    - name: Move Promtail binary to /usr/local/bin
      ansible.builtin.command:
        cmd: mv /usr/local/bin/promtail-linux-amd64 /usr/local/bin/promtail
    
    - name: Creating files 
      ansible.builtin.file:
       path: "{{ item.path }}" 
       state: touch
       mode: '0755'
      loop:
        - { path: '/etc/promtail-local-config.yaml' }
        - { path: '/etc/systemd/system/promtail.service' }
      notify: start promtail

    - name: Copy Promtail configuration file
      ansible.builtin.template:
        src: templates/prom-config.j2
        dest: /etc/promtail-local-config.yaml
        
    - name: Copy Promtail service file
      ansible.builtin.copy:
        src: files/promtail-service
        dest: /etc/systemd/system/promtail.service
      notify: start promtail


    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
      

   

    - name: Check Promtail service status
      ansible.builtin.command:
        cmd: systemctl status promtail.service
      register: promtail_status
      changed_when: false

    - name: Print Promtail service status
      ansible.builtin.debug:
        msg: "{{ promtail_status.stdout }}"
